baseURL = "/"
languageCode = "cs-cz"
title = "Osobní Rozcestník (Hugo)"

# Hugo by měl projít všechny adresáře, které obsahují Markdown
# a generovat z nich stránky.
disableKinds = ["taxonomy", "term"] # Vypne pokročilé funkce (tagy, kategorie) pro jednoduchý web

[params]
    description = "Statické stránky generované Hugem a stylované pomocí Bootstrapu."
