baseURL = "/"
languageCode = "cs-cz"
title = "Osobní Repozitář a Poznámky"
# Nastavte zde theme, pokud byste nechtěl plně customizovat
disableKinds = ["taxonomy", "term"] # Vypne nepotřebné funkce pro jednoduchý web

[params]
    description = "Materiály generované Hugem."
